"""
a list of idioms for game difficulty
"""

idioms = ["A drop in the ocean",
          "Actions speak louder than words",
          "Add fuel to the fire",
          "A penny for your thoughts",
          "Ball is in somebody's court",
          "Barking up the wrong tree",
          "Be a good catch",
          "Beat around the bush",
          "Bend over backwards",
          "Bite off more than you can chew",
          "Blow somebody away",
          "By the skin of your teeth",
          "Couldn't care less",
          "Cry over spilt milk",
          "Cry wolf",
          "Crunch time",
          "Curiosity killed the cat",
          "Cut corners",
          "Cut somebody some slack",
          "Cut to the chase",
          "Dig in your heels",
          "Stick to your guns",
          "Down to the wire",
          "Drive someone up the wall",
          "Get out of hand",
          "Get your head around it",
          "Give the benefit of the doubt",
          "Go down in flames",
          "Hear on the grapevine",
          "Hit the books",
          "It takes two to tango",
          "Judge a book by its cover",
          "Jump on the bandwagon",
          "Kill two birds with one stone",
          "Leave no stone unturned",
          "Let the cat out of the bag",
          "Make a long story short",
          "Miss the boat",
          "Once in a blue moon",
          "Piece of cake",
          "Pull a rabbit out of a hat",
          "Pull yourself together",
          "Run on fumes",
          "Sell somebody out",
          "Shoot from the hip",
          "Sit on the fence",
          "Skeleton crew",
          "Step up your game",
          "When pigs fly",
          "Whole nine yards",
          "Your guess is as good as mine"
          "a bitter pill",
          "a dime a dozen",
          "Achilles' heel",
          "actions speak louder than words",
          "add insult to injury"
          "all ears",
          "as easy as pie",
          "at the drop of a hat",
          "back to the drawing board",
          "ball is in your court",
          "barking up the wrong tree",
          "beat a dead horse",
          "beat around the bush",
          "beats me",
          "bent out of shape",
          "best of both worlds",
          "best thing since sliced bread",
          "bite off more than one can chew",
          "bite the bullet",
          "bite the dust",
          "blessing in disguise",
          "blow one's top",
          "bottom line",
          "break a leg",
          "break one's heart",
          "buck stops here",
          "burn the midnight oil",
          "by the skin of one's teeth",
          "call it a day",
          "catch some sleep",
          "caught my eye",
          "chew the cud",
          "chomp on the bit",
          "chow down",
          "clean as a whistle",
          "clam up",
          "cold shoulder",
          "cost an arm and leg",
          "cool down",
          "copy cat",
          "counting chickens before they hatch",
          "cut the cheese",
          "cut the rug",
          "crash course",
          "cry over spilt milk",
          "curiosity killed the cat",
          "cut corners",
          "cut it out",
          "devil's advocate",
          "don't give up one's day job",
          "down in the dumps",
          "drag one's feet",
          "drop a dime",
          "drop a line",
          "eager beaver",
          "easy does it",
          "elbow grease",
          "every dog has its day",
          "fall in love",
          "fed up with",
          "feel blue",
          "fire someone",
          "fit as a fiddle",
          "free-for-all",
          "from the horse's mouth",
          "give the benefit of the doubt",
          "hard feelings",
          "have a blast",
          "have eyes in the back of one's head",
          "have one's hands full",
          "heard it on the grapevine",
          "hit the books",
          "hit the hay",
          "hit the nail on the head",
          "hit the pavement",
          "hit the road",
          "hit the sack",
          "in over one's head",
          "it takes two to tango",
          "in the black",
          "in the heat of the moment",
          "in the long rum",
          "in the read",
          "in the zone",
          "jump the gun",
          "jump on the bandwagon",
          "jump to conclusion",
          "junk mail",
          "keep an eye on",
          "keep an eye out",
          "keep at bay",
          "keep in touch",
          "keeping up with the Jones's",
          "keep one's chin up",
          "keep one's eyes peeled",
          "keep one's fingers crossed",
          "kick the bucket",
          "kill two birds with one stone",
          "know something backwards and forwards",
          "know something inside and out",
          "know something like the back of one's hand",
          "last straw",
          "lend a hand",
          "let sleeping dogs lie",
          "let the cat out of the bag",
          "live and let live",
          "live hand to mouth",
          "lose track of",
          "low blow",
          "make a mountain out of a molehill",
          "make heads or tails of",
          "make up one's mind",
          "meet in the middle",
          "miss the boat",
          "nest egg",
          "New York minute",
          "nip it in the bud",
          "no horse in this race",
          "not on your life",
          "off one's rocker",
          "once in a blue moon",
          "on the ball",
          "on the cutting edge",
          "on point",
          "on the horn",
          "on the road",
          "on/off the wagon",
          "off the hook",
          "over one's head",
          "pay the piper",
          "pen is mightier than the sword",
          "penny for one's thoughts",
          "pick your poison",
          "piece of cake",
          "pull an all-nighter",
          "pull someone's leg",
          "pushing up daisies",
          "put all of one's eggs in one basket",
          "put the cart before the horse",
          "rain check",
          "raining cats and dogs",
          "rain or shine",
          "read between the lines",
          "read one's mind",
          "right as rain",
          "rub the wrong way",
          "see eye to eye",
          "sell the farm",
          "shoot the breeze",
          "sit on the fence",
          "speak of the devil",
          "sleep on it",
          "sleep with the fishes",
          "a snap",
          "spill the beans",
          "state of the art",
          "steal someone's thunder",
          "take it easy",
          "take the cake/biscuit",
          "take with a grain of salt",
          "under the weather",
          "until hell freezes over",
          "wet behind the ears",
          "when pigs fly",
          "whole nine yards",
          "wouldn't be caught dead",
          "yes-man",
          "zip it",
          "zero in"]
