idioms = ["A drop in the ocean",
          "Actions speak louder than words",
          "Add fuel to the fire",
          "A penny for your thoughts",
          "Ball is in somebody's court",
          "Barking up the wrong tree",
          "Be a good catch",
          "Beat around the bush",
          "Bend over backwards",
          "Bite off more than you can chew",
          "Blow somebody away",
          "By the skin of your teeth",
          "Couldn't care less",
          "Cry over spilt milk",
          "Cry wolf",
          "Crunch time",
          "Curiosity killed the cat",
          "Cut corners",
          "Cut somebody some slack",
          "Cut to the chase",
          "Dig in your heels",
          "Stick to your guns",
          "Down to the wire",
          "Drive someone up the wall",
          "Get out of hand",
          "Get your head around it",
          "Give the benefit of the doubt",
          "Go down in flames",
          "Hear on the grapevine",
          "Hit the books",
          "It takes two to tango",
          "Judge a book by its cover",
          "Jump on the bandwagon",
          "Kill two birds with one stone",
          "Leave no stone unturned",
          "Let the cat out of the bag",
          "Make a long story short",
          "Miss the boat",
          "Once in a blue moon",
          "Piece of cake",
          "Pull a rabbit out of a hat",
          "Pull yourself together",
          "Run on fumes",
          "Sell somebody out",
          "Shoot from the hip",
          "Sit on the fence",
          "Skeleton crew",
          "Step up your game",
          "When pigs fly",
          "Whole nine yards",
          "Your guess is as good as mine"]
